name: Build

on: [push, pull_request]

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-18.04", "windows-latest"]
        # vunit: ["4.4.0", "4.3.0", "4.2.0", "4.1.0"]
    runs-on: ${{ matrix.os }}
    steps: 
      
      # Node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      
      # GHDL
      - name: Install GHDL Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir ghdl
          cd ghdl
          wget https://github.com/ghdl/ghdl/releases/download/v0.37/ghdl-0.37-ubuntu16-mcode.tgz
          tar -xvzf ghdl-0.37-ubuntu16-mcode.tgz
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gnat-4.9/gnat-4.9-base_4.9.3-3ubuntu5_amd64.deb
          sudo dpkg --install gnat-4.9-base_4.9.3-3ubuntu5_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gnat-4.9/libgnat-4.9_4.9.3-3ubuntu5_amd64.deb
          sudo dpkg --install libgnat-4.9_4.9.3-3ubuntu5_amd64.deb
          echo "::add-path::$(pwd)/bin"
          cd ..
      - name: Install GHDL Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          mkdir ghdl
          cd ghdl
          wget https://github.com/ghdl/ghdl/releases/download/v0.37/ghdl-0.37-mingw32-mcode.zip
          Expand-Archive -Path ghdl.zip -DestinationPath ./
          echo "::add-path::$(pwd)/GHDL/0.37-mingw32-mcode/bin
          cd ..

      # Python + VUNit
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install vunit_hdl

      # Run the tests
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
